const IDS = {
  propLekki: "demo-prop-1",
  propVI:    "demo-prop-2",
  propAbuja: "demo-prop-3",
  propIbeju: "demo-prop-4",
  typeResidential: "demo-type-1",
  typeCommercial:  "demo-type-2",
  typeLand:        "demo-type-3",
  t1: "demo-tenant-1", t2: "demo-tenant-2", t3: "demo-tenant-3",
  t4: "demo-tenant-4", t5: "demo-tenant-5", t6: "demo-tenant-6",
  t7: "demo-tenant-7", t8: "demo-tenant-8", t9: "demo-tenant-9",
};

export const DEMO = {
  properties: [
    {
      id: IDS.propLekki, name: "Lekki Phase 1 Estate", address: "14 Admiralty Way",
      city: "Lagos", state: "Lagos", country: "Nigeria", currency: "NGN",
      status: "PARTIALLY_OCCUPIED", purchasePrice: 280_000_000, currentValue: 340_000_000,
      numberOfUnits: 6, notes: "Gated estate with 24/7 security",
      createdAt: new Date("2023-01-01"), updatedAt: new Date("2024-01-01"),
      propertyTypeId: IDS.typeResidential,
      propertyType: { id: IDS.typeResidential, name: "Residential", description: "Houses, apartments and residential estates", createdAt: new Date(), updatedAt: new Date() },
      units: [
        { id: "demo-u-1", propertyId: IDS.propLekki, unitNumber: "A1", unitType: "3 Bedroom", bedrooms: 3, bathrooms: 2, monthlyRent: 3_500_000, status: "OCCUPIED",    currency: "NGN", floor: null, size: null, notes: null },
        { id: "demo-u-2", propertyId: IDS.propLekki, unitNumber: "A2", unitType: "3 Bedroom", bedrooms: 3, bathrooms: 2, monthlyRent: 3_500_000, status: "OCCUPIED",    currency: "NGN", floor: null, size: null, notes: null },
        { id: "demo-u-3", propertyId: IDS.propLekki, unitNumber: "B1", unitType: "2 Bedroom", bedrooms: 2, bathrooms: 1, monthlyRent: 2_500_000, status: "OCCUPIED",    currency: "NGN", floor: null, size: null, notes: null },
        { id: "demo-u-4", propertyId: IDS.propLekki, unitNumber: "B2", unitType: "2 Bedroom", bedrooms: 2, bathrooms: 1, monthlyRent: 2_500_000, status: "VACANT",      currency: "NGN", floor: null, size: null, notes: null },
        { id: "demo-u-5", propertyId: IDS.propLekki, unitNumber: "C1", unitType: "1 Bedroom", bedrooms: 1, bathrooms: 1, monthlyRent: 1_800_000, status: "VACANT",      currency: "NGN", floor: null, size: null, notes: null },
        { id: "demo-u-6", propertyId: IDS.propLekki, unitNumber: "C2", unitType: "1 Bedroom", bedrooms: 1, bathrooms: 1, monthlyRent: 1_800_000, status: "MAINTENANCE", currency: "NGN", floor: null, size: null, notes: null },
      ],
      expenses: [], photos: [], documents: [],
    },
    {
      id: IDS.propVI, name: "Victoria Island Office Complex", address: "Plot 1234 Adeola Odeku Street",
      city: "Lagos", state: "Lagos", country: "Nigeria", currency: "NGN",
      status: "PARTIALLY_OCCUPIED", purchasePrice: 450_000_000, currentValue: 520_000_000,
      numberOfUnits: 4, notes: "Grade-A office space",
      createdAt: new Date("2023-02-01"), updatedAt: new Date("2024-01-01"),
      propertyTypeId: IDS.typeCommercial,
      propertyType: { id: IDS.typeCommercial, name: "Commercial", description: "Offices, shops and commercial buildings", createdAt: new Date(), updatedAt: new Date() },
      units: [
        { id: "demo-u-7",  propertyId: IDS.propVI, unitNumber: "Floor 1", unitType: "Open Plan Office",   bedrooms: null, bathrooms: null, monthlyRent: 8_000_000,  status: "OCCUPIED", currency: "NGN", floor: "1", size: null, notes: null },
        { id: "demo-u-8",  propertyId: IDS.propVI, unitNumber: "Floor 2", unitType: "Open Plan Office",   bedrooms: null, bathrooms: null, monthlyRent: 8_000_000,  status: "OCCUPIED", currency: "NGN", floor: "2", size: null, notes: null },
        { id: "demo-u-9",  propertyId: IDS.propVI, unitNumber: "Floor 3", unitType: "Partitioned Office", bedrooms: null, bathrooms: null, monthlyRent: 7_500_000,  status: "VACANT",   currency: "NGN", floor: "3", size: null, notes: null },
        { id: "demo-u-10", propertyId: IDS.propVI, unitNumber: "Floor 4", unitType: "Penthouse Suite",    bedrooms: null, bathrooms: null, monthlyRent: 12_000_000, status: "VACANT",   currency: "NGN", floor: "4", size: null, notes: null },
      ],
      expenses: [], photos: [], documents: [],
    },
    {
      id: IDS.propAbuja, name: "Maitama Luxury Apartments", address: "22 Aguiyi Ironsi Street",
      city: "Abuja", state: "FCT", country: "Nigeria", currency: "NGN",
      status: "OCCUPIED", purchasePrice: 190_000_000, currentValue: 230_000_000,
      numberOfUnits: 4, notes: null,
      createdAt: new Date("2023-03-01"), updatedAt: new Date("2024-01-01"),
      propertyTypeId: IDS.typeResidential,
      propertyType: { id: IDS.typeResidential, name: "Residential", description: "Houses, apartments and residential estates", createdAt: new Date(), updatedAt: new Date() },
      units: [
        { id: "demo-u-11", propertyId: IDS.propAbuja, unitNumber: "101", unitType: "4 Bedroom Duplex", bedrooms: 4, bathrooms: 3, monthlyRent: 5_000_000, status: "OCCUPIED", currency: "NGN", floor: "1", size: null, notes: null },
        { id: "demo-u-12", propertyId: IDS.propAbuja, unitNumber: "102", unitType: "4 Bedroom Duplex", bedrooms: 4, bathrooms: 3, monthlyRent: 5_000_000, status: "OCCUPIED", currency: "NGN", floor: "1", size: null, notes: null },
        { id: "demo-u-13", propertyId: IDS.propAbuja, unitNumber: "201", unitType: "3 Bedroom Flat",   bedrooms: 3, bathrooms: 2, monthlyRent: 3_800_000, status: "OCCUPIED", currency: "NGN", floor: "2", size: null, notes: null },
        { id: "demo-u-14", propertyId: IDS.propAbuja, unitNumber: "202", unitType: "3 Bedroom Flat",   bedrooms: 3, bathrooms: 2, monthlyRent: 3_800_000, status: "OCCUPIED", currency: "NGN", floor: "2", size: null, notes: null },
      ],
      expenses: [], photos: [], documents: [],
    },
    {
      id: IDS.propIbeju, name: "Ibeju-Lekki Land Bank", address: "Km 42 Lekki-Epe Expressway",
      city: "Ibeju-Lekki", state: "Lagos", country: "Nigeria", currency: "NGN",
      status: "VACANT", purchasePrice: 60_000_000, currentValue: 95_000_000,
      numberOfUnits: 0, notes: "C of O obtained. 2 plots.",
      createdAt: new Date("2023-04-01"), updatedAt: new Date("2024-01-01"),
      propertyTypeId: IDS.typeLand,
      propertyType: { id: IDS.typeLand, name: "Land", description: "Land and undeveloped plots", createdAt: new Date(), updatedAt: new Date() },
      units: [], expenses: [], photos: [], documents: [],
    },
  ],

  tenants: [
    { id: IDS.t1, name: "Adaeze Okonkwo",    email: "adaeze@example.com",  phone: "08031234567", propertyId: IDS.propLekki,  monthlyRent: 3_500_000, securityDeposit: 7_000_000,  moveInDate: new Date("2024-01-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propLekki,  name: "Lekki Phase 1 Estate",           currency: "NGN" } },
    { id: IDS.t2, name: "Emeka Nwosu",       email: "emeka@example.com",   phone: "08041234567", propertyId: IDS.propLekki,  monthlyRent: 3_500_000, securityDeposit: 7_000_000,  moveInDate: new Date("2024-01-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propLekki,  name: "Lekki Phase 1 Estate",           currency: "NGN" } },
    { id: IDS.t3, name: "Fatima Aliyu",      email: "fatima@example.com",  phone: "08051234567", propertyId: IDS.propLekki,  monthlyRent: 2_500_000, securityDeposit: 5_000_000,  moveInDate: new Date("2024-01-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propLekki,  name: "Lekki Phase 1 Estate",           currency: "NGN" } },
    { id: IDS.t4, name: "Chidi Enterprises", email: "chidi@example.com",   phone: "08061234567", propertyId: IDS.propVI,     monthlyRent: 8_000_000, securityDeposit: 16_000_000, moveInDate: new Date("2024-02-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propVI,     name: "Victoria Island Office Complex", currency: "NGN" } },
    { id: IDS.t5, name: "Zenith Consulting", email: "zenith@example.com",  phone: "08071234567", propertyId: IDS.propVI,     monthlyRent: 8_000_000, securityDeposit: 16_000_000, moveInDate: new Date("2024-02-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propVI,     name: "Victoria Island Office Complex", currency: "NGN" } },
    { id: IDS.t6, name: "Bola Tinubu-James", email: "bola@example.com",    phone: "08081234567", propertyId: IDS.propAbuja,  monthlyRent: 5_000_000, securityDeposit: 10_000_000, moveInDate: new Date("2024-03-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propAbuja,  name: "Maitama Luxury Apartments",      currency: "NGN" } },
    { id: IDS.t7, name: "Ngozi Adeyemi",     email: "ngozi@example.com",   phone: "08091234567", propertyId: IDS.propAbuja,  monthlyRent: 5_000_000, securityDeposit: 10_000_000, moveInDate: new Date("2024-03-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propAbuja,  name: "Maitama Luxury Apartments",      currency: "NGN" } },
    { id: IDS.t8, name: "Tunde Bakare",      email: "tunde@example.com",   phone: "08001234567", propertyId: IDS.propAbuja,  monthlyRent: 3_800_000, securityDeposit: 7_600_000,  moveInDate: new Date("2024-03-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propAbuja,  name: "Maitama Luxury Apartments",      currency: "NGN" } },
    { id: IDS.t9, name: "Amina Suleiman",    email: "amina@example.com",   phone: "08011234567", propertyId: IDS.propAbuja,  monthlyRent: 3_800_000, securityDeposit: 7_600_000,  moveInDate: new Date("2024-03-01"), moveOutDate: null, createdAt: new Date("2024-01-01"), updatedAt: new Date(), property: { id: IDS.propAbuja,  name: "Maitama Luxury Apartments",      currency: "NGN" } },
  ],

  obligations: [
    { id: "demo-ob-1",  propertyId: IDS.propLekki,  leaseId: "demo-l-1", unitId: "demo-u-1",  amountDue: 3_500_000, amountPaid: 3_500_000, status: "PAID",           dueDate: new Date(Date.now() - 60*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Adaeze Okonkwo" },    property: { name: "Lekki Phase 1 Estate" } } },
    { id: "demo-ob-2",  propertyId: IDS.propLekki,  leaseId: "demo-l-2", unitId: "demo-u-2",  amountDue: 3_500_000, amountPaid: 3_500_000, status: "PAID",           dueDate: new Date(Date.now() - 60*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Emeka Nwosu" },       property: { name: "Lekki Phase 1 Estate" } } },
    { id: "demo-ob-3",  propertyId: IDS.propLekki,  leaseId: "demo-l-3", unitId: "demo-u-3",  amountDue: 2_500_000, amountPaid: 2_500_000, status: "PAID",           dueDate: new Date(Date.now() - 60*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Fatima Aliyu" },      property: { name: "Lekki Phase 1 Estate" } } },
    { id: "demo-ob-4",  propertyId: IDS.propVI,     leaseId: "demo-l-4", unitId: "demo-u-7",  amountDue: 8_000_000, amountPaid: 8_000_000, status: "PAID",           dueDate: new Date(Date.now() - 60*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Chidi Enterprises" }, property: { name: "Victoria Island Office Complex" } } },
    { id: "demo-ob-5",  propertyId: IDS.propVI,     leaseId: "demo-l-5", unitId: "demo-u-8",  amountDue: 8_000_000, amountPaid: 8_000_000, status: "PAID",           dueDate: new Date(Date.now() - 60*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Zenith Consulting" }, property: { name: "Victoria Island Office Complex" } } },
    { id: "demo-ob-6",  propertyId: IDS.propAbuja,  leaseId: "demo-l-6", unitId: "demo-u-11", amountDue: 5_000_000, amountPaid: 5_000_000, status: "PAID",           dueDate: new Date(Date.now() - 60*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Bola Tinubu-James" }, property: { name: "Maitama Luxury Apartments" } } },
    { id: "demo-ob-7",  propertyId: IDS.propLekki,  leaseId: "demo-l-1", unitId: "demo-u-1",  amountDue: 3_500_000, amountPaid: 3_500_000, status: "PAID",           dueDate: new Date(Date.now() - 30*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Adaeze Okonkwo" },    property: { name: "Lekki Phase 1 Estate" } } },
    { id: "demo-ob-8",  propertyId: IDS.propVI,     leaseId: "demo-l-4", unitId: "demo-u-7",  amountDue: 8_000_000, amountPaid: 4_000_000, status: "PARTIALLY_PAID", dueDate: new Date(Date.now() - 30*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Chidi Enterprises" }, property: { name: "Victoria Island Office Complex" } } },
    { id: "demo-ob-9",  propertyId: IDS.propAbuja,  leaseId: "demo-l-6", unitId: "demo-u-11", amountDue: 5_000_000, amountPaid: 0,         status: "OVERDUE",        dueDate: new Date(Date.now() - 10*86400000), periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Bola Tinubu-James" }, property: { name: "Maitama Luxury Apartments" } } },
    { id: "demo-ob-10", propertyId: IDS.propLekki,  leaseId: "demo-l-2", unitId: "demo-u-2",  amountDue: 3_500_000, amountPaid: 0,         status: "DUE",            dueDate: new Date(Date.now() + 3*86400000),  periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Emeka Nwosu" },       property: { name: "Lekki Phase 1 Estate" } } },
    { id: "demo-ob-11", propertyId: IDS.propVI,     leaseId: "demo-l-5", unitId: "demo-u-8",  amountDue: 8_000_000, amountPaid: 0,         status: "PENDING",        dueDate: new Date(Date.now() + 5*86400000),  periodStart: new Date(), periodEnd: new Date(), lease: { tenant: { name: "Zenith Consulting" }, property: { name: "Victoria Island Office Complex" } } },
  ],

  expenses: [
    { id: "demo-e-1",  propertyId: IDS.propLekki,  category: "REPAIRS",        description: "Roof leak repair — Block A",     amount: 850_000,   currency: "NGN", expenseDate: new Date("2025-02-10"), vendor: "Apex Contractors",         receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-02-10"), property: { id: IDS.propLekki,  name: "Lekki Phase 1 Estate",           currency: "NGN" } },
    { id: "demo-e-2",  propertyId: IDS.propLekki,  category: "UTILITIES",      description: "Borehole pump replacement",      amount: 420_000,   currency: "NGN", expenseDate: new Date("2025-03-05"), vendor: "AquaTech Ltd",             receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-03-05"), property: { id: IDS.propLekki,  name: "Lekki Phase 1 Estate",           currency: "NGN" } },
    { id: "demo-e-3",  propertyId: IDS.propLekki,  category: "SERVICE_CHARGE", description: "Estate management Q1",           amount: 1_200_000, currency: "NGN", expenseDate: new Date("2025-01-15"), vendor: "Lekki Estate Mgmt",        receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-01-15"), property: { id: IDS.propLekki,  name: "Lekki Phase 1 Estate",           currency: "NGN" } },
    { id: "demo-e-4",  propertyId: IDS.propLekki,  category: "INSURANCE",      description: "Annual building insurance",      amount: 650_000,   currency: "NGN", expenseDate: new Date("2025-01-02"), vendor: "Leadway Assurance",        receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-01-02"), property: { id: IDS.propLekki,  name: "Lekki Phase 1 Estate",           currency: "NGN" } },
    { id: "demo-e-5",  propertyId: IDS.propVI,     category: "REPAIRS",        description: "HVAC servicing — all floors",    amount: 2_300_000, currency: "NGN", expenseDate: new Date("2025-02-20"), vendor: "CoolAir Services",         receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-02-20"), property: { id: IDS.propVI,     name: "Victoria Island Office Complex", currency: "NGN" } },
    { id: "demo-e-6",  propertyId: IDS.propVI,     category: "UTILITIES",      description: "Generator diesel — Feb",         amount: 980_000,   currency: "NGN", expenseDate: new Date("2025-02-28"), vendor: "Total Energies",           receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-02-28"), property: { id: IDS.propVI,     name: "Victoria Island Office Complex", currency: "NGN" } },
    { id: "demo-e-7",  propertyId: IDS.propVI,     category: "MANAGEMENT_FEE", description: "Property management fee Q1",    amount: 3_500_000, currency: "NGN", expenseDate: new Date("2025-01-31"), vendor: "Prime Properties",         receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-01-31"), property: { id: IDS.propVI,     name: "Victoria Island Office Complex", currency: "NGN" } },
    { id: "demo-e-8",  propertyId: IDS.propVI,     category: "INSURANCE",      description: "Commercial property insurance",  amount: 1_800_000, currency: "NGN", expenseDate: new Date("2025-01-05"), vendor: "AXA Mansard",              receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-01-05"), property: { id: IDS.propVI,     name: "Victoria Island Office Complex", currency: "NGN" } },
    { id: "demo-e-9",  propertyId: IDS.propAbuja,  category: "REPAIRS",        description: "Plumbing overhaul — Block 1",    amount: 560_000,   currency: "NGN", expenseDate: new Date("2025-03-12"), vendor: "Abuja Plumbers Co.",       receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-03-12"), property: { id: IDS.propAbuja,  name: "Maitama Luxury Apartments",      currency: "NGN" } },
    { id: "demo-e-10", propertyId: IDS.propAbuja,  category: "SERVICE_CHARGE", description: "Maitama estate levy Q1",         amount: 900_000,   currency: "NGN", expenseDate: new Date("2025-01-20"), vendor: "Maitama Residents Assoc.", receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-01-20"), property: { id: IDS.propAbuja,  name: "Maitama Luxury Apartments",      currency: "NGN" } },
    { id: "demo-e-11", propertyId: IDS.propAbuja,  category: "UTILITIES",      description: "Solar inverter maintenance",     amount: 310_000,   currency: "NGN", expenseDate: new Date("2025-02-14"), vendor: "SolarMax NG",              receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-02-14"), property: { id: IDS.propAbuja,  name: "Maitama Luxury Apartments",      currency: "NGN" } },
    { id: "demo-e-12", propertyId: IDS.propIbeju,  category: "OTHER",          description: "Survey & beaconing renewal",     amount: 250_000,   currency: "NGN", expenseDate: new Date("2025-01-08"), vendor: "Surveyor Adebayo",         receiptUrl: null, reference: null, notes: null, unitId: null, createdAt: new Date("2025-01-08"), property: { id: IDS.propIbeju,  name: "Ibeju-Lekki Land Bank",          currency: "NGN" } },
  ],
} as const;
